### ISSUE TITLE
Vaping experiment (ALID)

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#7]
There are issues with how this experiment is showing up across conditions

ALID_2 and ALID_3 both have associated comments that should be populating the feed. Currently none of these comments are showing up.

ALID_1 currently none of the post photos are populating. ALID_1 does not have any associated comments so that is fine. When the feed is put into this condition, it also puts the text from a vaping condition onto one of the RVID posts (from Jackie Turner) so there is a mix up happening there as well.

**Comment by brosshirt** [comment]
I think this is resolved, I would just like your confirmation before I close the issue :).

**Comment by marlyn-p** [comment]
ALID_2 & ALID_3 the comments seem to be working correctly now.

ALID_1 the 4th image is not populating, from Mary Chester
<img width="568" alt="Screen Shot 2022-08-17 at 3 44 38 PM" src="https://user-images.githubusercontent.com/109811473/185228925-a21e3868-0dba-4888-a120-a6a4ad43e6c0.png">

RVID_4
 I am still seeing the issue with Jackie Turner's post (a photo of wings), it has the post text from a vaping condition

**Comment by brosshirt** [comment]
The Mary Chester image is loading for me, let me know if other people are having the same problem as well and I'll see what can be done. And what would you like the wings post text to be?

**Comment by brosshirt** [comment]
What would you like the post text to say?

**Comment by marlyn-p** [comment]
Here is the text for Jackie Turner's post to accompany the picture of wings:

@HealthForEveryone ambassador here to encourage you to do something with a friend this week. Something like sharing a meal. You can't go wrong with wings!

#wingWednesday #yum #foodie
